# **Team Tors** | **Machine Learning Hackathon** 

~ Vikash Kumar

**Importing the libraries**

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

**Data Collection and Data Processing**

In [2]:
# Importing dataset to pandas library
training_data = pd.read_csv('Phising_Training_Dataset.csv')
testing_data = pd.read_csv('Phising_Testing_Dataset.csv')

In [19]:
#To get knowledge about the packages
pd.read_csv?

In [3]:
#Printing the first 5 rows of the training dataset
training_data.head()

key  having_IP  URL_Length  Shortining_Service  having_At_Symbol  \
0  12344         -1           1                   1                 1   
1  12345          1           1                   1                 1   
2  12346          1           0                   1                 1   
3  12347          1           0                   1                 1   
4  12348          1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  ...  popUpWidnow  Iframe  age_of_domain  \
0                           -1  ...            1       1             -1   
1                           -1  ...            1       1             -1   
2                           -1  ...            1       1              1   
3                            1  ...            1       1             -1   
4                           -1  ...           -1       1             -1   

   DNSRecord  web_traffic  Page_Rank  Google_Index  Links_pointing_to_page  \
0         -1           -1         -1             1                       1   
1         -1            0         -1             1                       1   
2         -1            1         -1             1                       0   
3         -1            1         -1             1                      -1   
4         -1            0         -1             1                       1   

   Statistical_report  Result  
0                  -1      -1  
1                   1      -1  
2                  -1      -1  
3                   1      -1  
4                   1       1  

[5 rows x 32 columns]

In [4]:
#Printing the first 5 rows of the testing dataset
testing_data.head()

key  having_IP  URL_Length  Shortining_Service  having_At_Symbol  \
0  21338          1           1                   1                 1   
1  21339          1          -1                   1                 1   
2  21340          1          -1                   1                 1   
3  21341         -1          -1                  -1                 1   
4  21342          1          -1                   1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                         1              1                 -1               1   
1                         1             -1                  0              -1   
2                         1             -1                  0               0   
3                        -1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  ...  RightClick  popUpWidnow  Iframe  \
0                           -1  ...           1            1       1   
1                            1  ...           1            1       1   
2                           -1  ...          -1           -1      -1   
3                            1  ...           1           -1      -1   
4                           -1  ...           1            1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0              1          1            1          1            -1   
1             -1         -1            0         -1            -1   
2              1         -1            1         -1             1   
3              1         -1            1         -1             1   
4              1          1            1         -1             1   

   Links_pointing_to_page  Statistical_report  
0                       0                   1  
1                       0                   1  
2                       1                  -1  
3                       1                  -1  
4                       0                   1  

[5 rows x 31 columns]

In [5]:
#Total number of rows and columns in the dataset
training_data.shape

(8955, 32)

In [6]:
testing_data.shape

(2100, 31)

In [7]:
training_data['Result'].value_counts()

 1    5034
-1    3921
Name: Result, dtype: int64

In [8]:
#Separating the data and levels
X = training_data.drop(columns='Result', axis=1)
Y = training_data['Result']
X = X.values

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=3) 

In [10]:
print(X)
print(Y)

[[12344    -1     1 ...     1     1    -1]
 [12345     1     1 ...     1     1     1]
 [12346     1     0 ...     1     0    -1]
 ...
 [21296     1    -1 ...     1     0     1]
 [21297    -1    -1 ...     1     1     1]
 [21298    -1    -1 ...    -1     1    -1]]
0      -1
1      -1
2      -1
3      -1
4       1
       ..
8950    1
8951   -1
8952   -1
8953   -1
8954   -1
Name: Result, Length: 8955, dtype: int64


In [11]:
print(X_train.shape, X_test.shape,Y_train.shape,Y_test.shape)

(7164, 31) (1791, 31) (7164,) (1791,)


# Model Training

In [12]:
model = LogisticRegression()

In [13]:
model.fit(X_train, Y_train)

LogisticRegression()

In [14]:
X_train_prediction = model.predict(X_train)
train_data_accuracy = accuracy_score(X_train_prediction,Y_train) 
print(train_data_accuracy)

0.9271356783919598


In [15]:
X_test_prediction = model.predict(X_test)
train_data_accuracy = accuracy_score(X_test_prediction,Y_test) 
print(train_data_accuracy)

0.9195979899497487


In [20]:
input_data = (21339,1,-1,1,1,1,-1,0,-1,1,1,-1,1,1,-1,-1,1,1,0,0,1,1,1,-1,-1,-1,0,-1,-1,0,1)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = model.predict(input_data_reshaped)
print(prediction)
if (prediction[0]== 0):
      print("The website is suspicious")
elif (prediction[0]== 1):
  print("The website is legitimate")
else:
  print("The person is phishing")

[-1]
The person is phishing


# Submission File

In [17]:
updated_predict = model.predict(X)
updated_predict[updated_predict<0] = 0
sub = pd.DataFrame({'key' : training_data['key'],'Result' : updated_predict})
sub.to_csv("submission_training_data.csv", index=False)

In [18]:
testing_dat = testing_data.values
updated_test_predict = model.predict(testing_dat)
updated_test_predict[updated_test_predict<0] = 0 
submit = pd.DataFrame({'key' : testing_data['key'],'Result' : updated_test_predict})
submit.to_csv("submission_testing_data.csv", index=False)